typography_spectrum: 0.3817370815668255
color:
  brandStrength: 0.6225279266946018
  lightness: 0.011110542342066765
  saturation: 0.4557008573319763
  rhythmicContrast: 0.06628741906024516
  brandColors:
    - '#F8F9FC'
    - '#224FAA'
    - '#A62626'
    - '#3D588F'
    - '#C7CAD1'
layout_spectrum: 0.16856879461556673
name: Fitness Instructor - Ductor
navigation:
  - name: Guides
    url: 'http://fitnessductor.com'
    type: external
description: We will instruct you how to be fit!
